server:
  port: 8081
# DataSource Config
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.111:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: LYX5201314
      initial-size: 1
      min-idle: 1
      max-active: 20
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
#    hikari:
#      max-lifetime: 9999999
#  security:
#    user:
#      name: LeiYuXin
#      password: LYX5201314
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
com:
  iloveleiyuxin:
    websitmanager:
      jwt:
        header: Authorization
        expire: 604800 #7天，秒单位
        secret: ji8n3439n439n43ld9ne9343fdfer49h