server:
  port: 8081
# DataSource Config
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.124:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      #      url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      #      password: LYX5201314
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
  redis:
    host: 192.168.1.124
    port: 6379  #可不配，因为底层默认值为6379
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
#    hikari:
#      max-lifetime: 9999999
#  security:
#    user:
#      name: LeiYuXin
#      password: LYX5201314
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
http:
  #最大连接数
  maxTotal: 100
  defaultMaxPerRoute: 20
  #连接超时时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

com:
  iloveleiyuxin:
    websitmanager:
      jwt:
        header: Authorization
        expire: 604800 #7天，秒单位
        secret: ji8n3439n439n43ld9ne9343fdfer49h